/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Backend;


import io.javalin.Javalin;

public class App {

    public static void main(String[] args) {
        Javalin javaServer = Javalin.create().start(7000);
        javaServer.get("/", ctx -> ctx.result("Group project"));

    }

}
